### ISSUE TITLE
Player's current and total times are cut off at the bottom

### ISSUE THREAD

**Issue by willemw12** [bottiger/SoundWaves#32] opened 2015-04-04 09:22 UTC
The player's "current play position" and "total" times above the "play position" slider are cut off at the bottom. On a Nexus 7 2013.

**Comment by bottiger** [comment] 2015-04-04 19:24
Good to know. I'll see if I can find an easy solution for this to include asap. However, the big tablet refactoring will have to wait a bit.

**Comment by willemw12** [comment] 2015-04-04 19:56
Haven't checked the source code, but do you scale according to the display density (http://developer.android.com/guide/practices/screens_support.html)?

**Comment by bottiger** [comment] 2015-04-20 23:47
@willemw12  Can you please provide a screenshot? I can not reproduce this on my Nexus 7

**Comment by willemw12** [comment] 2015-04-21 08:22
Nexus 7, 2013, stock Android.

![screenshot](https://cloud.githubusercontent.com/assets/1303481/7248065/4276cc3c-e810-11e4-8283-b9d542497b04.png)

**Comment by bottiger** [comment] 2015-04-21 08:53
@willemw12  Thank you for this.

However, I find it very odd since my Nexus 7 (also 2013, also stock) do no have this problem.
I will try to rewrite the code in a more robust way when looking at the player for the next release

**Comment by bottiger** [comment] 2015-05-13 15:29
@willemw12 has it been fixed in 0.94.2?

**Comment by willemw12** [comment] 2015-05-13 15:39
Yes, it has been fixed.

    Android Settings --> Display --> Font size : Large

may have something to do with it. I have seen the same problem in some of the other media player apps (don't remember which ones).

**Comment by bottiger** [comment] 2015-05-13 15:44
God point about the font size. Never thought of that.

But I'm glad it's fixed.

**Closed by bottiger** 2015-05-13 15:44 UTC
