### ISSUE TITLE
Import action not working

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#63] opened 2015-09-18 22:58 UTC
In release 0.106 import option is not working. When i try to import an .opml file nothing is done.

I´ve tried to put it in sd card and in internal storage but soundwaves always says that ther is no podcasts.opml file.

My android system is 4.3.

**Comment by smarquespt** [comment] 2015-09-20 21:12
@bottiger 

no problem in f-droid build. only in play build.

**Comment by bottiger** [comment] 2015-09-20 22:32
@smarquespt This should also be fixed in the upcoming 0.108, but it's a bit more phone specific, so please reopen this if the issue is not fixed.

**Closed by bottiger** 2015-09-20 22:32 UTC

**Comment by smarquespt** [comment] 2015-09-26 09:33
Also fixed as stated in https://github.com/bottiger/SoundWaves/issues/64
