### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#23] opened 2015-04-01 08:58 UTC
Import/export option isn´t working on 0.86 release.

**Comment by bottiger** [comment] 2015-04-01 17:00
Which version of android are you running? And does your device have an SD card or not?

(On an unrelated note, I won't be able to do any programming this week)

**Comment by smarquespt** [comment] 2015-04-01 21:17
> Which version of android are you running

I´m on 4.3

> And does your device have an SD card or not?

Yes

> (On an unrelated note, I won't be able to do any programming this week)

No problem. Take your time.

**Comment by bottiger** [comment] 2015-04-03 13:46
I'm reopening this issue. I think there are some issues I need to investigate. I'm not sure if android can write to external storage while connected to a computer.

**Comment by bottiger** [comment] 2015-04-16 15:31
I hope the problem is fixed now, but I am not completely sure

**Closed by bottiger** 2015-04-16 15:31 UTC
Labels: bug
